version: 2
references:
  container_config: &circleci-commitlint
    docker:
      - image: williamlauze/circleci-commitlint:latest
    working_directory: /www
jobs:
  commitlint:
    <<: *circleci-commitlint
    steps:
      - checkout
      - run:
          name: commitlint
          command: |
            /bin/sh /.scripts/commitlint_range.sh

workflows:
  version: 2
  my_pipeline:
    jobs:
      - commitlint